import type { Metadata } from 'next'
import './globals.css'
import HeaderComponent from '@/components/header'
import { Readex_Pro } from 'next/font/google'
import Footer from '@/components/footer'
import UserContextProvider from '@/context/userContext'

const Readex = Readex_Pro({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Foods',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${Readex.className} antialiased`}>
        <UserContextProvider>
          <HeaderComponent />
          {children}
          <Footer />
        </UserContextProvider>
      </body>
    </html>
  )
}
